### PR TITLE
cleanup rviz errors

### LINKED ISSUE #257: TIFFFieldWithTag warnings with pr2_description
Similar to https://github.com/PR2/pr2_common/issues/256, I'm getting hundreds of these warnings:

> TIFFFetchNormalTag: Warning, Incompatible type for "RichTIFFIPTC"; tag ignored.
> TIFFFieldWithTag: Internal error, unknown tag 0x829a.

### PR DESCRIPTION
**Pull request by v4hn**
This converts a number of texture files and the kinect2 mesh file to different formats
to finally get rid of a number of well-known errors every time you loadup RViz with the model loaded.

@k-okada I guess your group also has an interested to see this merged :sunglasses: .

The commits should also be merged into `melodic-devel`, but we are "still" stuck with kinetic-devel for now.

Fixes #257 .

### CODE REVIEW

**Comment by v4hn** [comment]
The larger (first) commit 6aa7e59 was generated automatically by converting all `*.tif` files to `.png` and replacing all file references to such files appropriately.

For e78d8df I opened and exported the old mesh via meshlab.

**Comment by k-okada** [comment]
@v4hn since we already release kinetic package from `melodic-devel` branch, I think this patch should target to `melodic-devel` branch and release into kinetic/melodic. 
https://github.com/ros/rosdistro/pull/21018/files
https://github.com/PR2/pr2_common/network

**Comment by v4hn** [comment]
True, somehow we missed that as we use a custom branch on our own system.
I just rebased on top of `melodic-devel`.
Please review and merge if this is ok with you.

**Review by lianghongzhuo — APPROVED** [review]
I like this pull request

**Pull request merged**
