### PR TITLE
Changed urdf to use optenvs instead of params to keep consistent

### PR DESCRIPTION
**Pull request by archielee**
Keep parameter passing scheme the same with optenvs for Kinect status

### CODE REVIEW

**Comment by k-okada** [comment]
if this solves following problem, please release new version, I'm using 1.11.11 from shadow-fixed and had following error

```
$ roslaunch pr2_description upload_pr2.launch 
... logging to /home/k-okada/.ros/log/ecec4dd4-ca84-11e5-b0f8-68f728079ca1/roslaunch-kokada-t440s-3895.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
WARNING: disk usage in log directory [/home/k-okada/.ros/log] is over 1GB.
It's recommended that you use the 'rosclean' command.

 is not a 'bool' type
The traceback for the exception was written to the log file
$ rosversion pr2_description
1.11.11
```

**Comment by archielee** [comment]
Hi, sorry @k-okada. We're having a small problem at the moment with another issue on the Kinect2 side and just haven't gotten to making a new version tag. If you pull the current version off github, it should be a temporary fix until we get this pushed to the buildfarm.

Edit: make sure you set an optenv if you intend on using a Kinect (either 1 or 2). Version tag will be released ASAP (I'll try to get it out tomorrow)

**Comment by archielee** [comment]
New tag has been created

**Comment by k-okada** [comment]
Thank you!! (^-^)

2016年2月5日金曜日、Archie Leenotifications@github.comさんは書きました:

> New tag has been created
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PR2/pr2_common/pull/248#issuecomment-179919663.

## 

## 

◉ Kei Okada

**Pull request merged**
