### PR TITLE
Prepend xacro tags with xacro xml namespace

### PR DESCRIPTION
**Pull request by davetcoleman**
When using in Kinetic xacro outputs the following warning:

```
deprecated: xacro tags should be prepended with 'xacro' xml namespace.
Use the following script to fix incorrect usage:
        find . -iname "*.xacro" | xargs sed -i 's#<\([/]\?\)\(if\|unless\|include\|arg\|property\|macro\|insert_block\)#<\1xacro:\2#g'
```

so i did that.

### CODE REVIEW

**Comment by archielee** [comment]
ping @TheDash

**Comment by davetcoleman** [comment]
@v4hn do you know who is maintaining the PR2 repos now?

**Comment by hvpandya** [comment]
Would be great to have #259 and #260 merged

**Comment by shupx** [comment]
> When using in Kinetic xacro outputs the following warning:
> 
> ```
> deprecated: xacro tags should be prepended with 'xacro' xml namespace.
> Use the following script to fix incorrect usage:
>         find . -iname "*.xacro" | xargs sed -i 's#<\([/]\?\)\(if\|unless\|include\|arg\|property\|macro\|insert_block\)#<\1xacro:\2#g'
> ```
> 
> so i did that.

excellent! This helps me a lot! it is necessary to fix this for namespace of xacro.

**Pull request merged**
